services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=studioghiblibackoffice
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=L@U_4btAYWwW2G:_pc~JDm)[uq;[(ZJ
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}
