version: '3.3'
services:
  # app:
  #   image: thunderxx/studioghiblibackoffice
  #   build:
  #     context: .
  #     dockerfile: ./build/production.Dockerfile
  #   environment:
  #     - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
  #     - TYPEORM_HOST=${TYPEORM_HOST}
  #     - TYPEORM_USERNAME=${TYPEORM_USERNAME}
  #     - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
  #     - TYPEORM_DATABASE=${TYPEORM_DATABASE}
  #     - TYPEORM_PORT=${TYPEORM_PORT}
  #     - TYPEORM_LOGGING=${TYPEORM_LOGGING}
  #     - TYPEORM_ENTITIES=${TYPEORM_ENTITIES}
  #     - TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}
  #     - TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}
  #     - TYPEORM_MIGRATIONS_TABLE_NAME=${TYPEORM_MIGRATIONS_TABLE_NAME}
  #     - EMAIL_HOST=${EMAIL_HOST}
  #     - EMAIL_PORT=${EMAIL_PORT}
  #     - EMAIL_USER=${EMAIL_USER}
  #     - EMAIL_PASSWORD=${EMAIL_PASSWORD}
  #     - ENCRYPTION_KEY=${ENCRYPTION_KEY}
  #     - HASH_FUNCTION=${HASH_FUNCTION}
  #     - CIPHER_ALGORITM=${CIPHER_ALGORITM}
  #     - APP_NAME=${APP_NAME}
  #     - REQUIRED_TWO_FACTOR=${REQUIRED_TWO_FACTOR}
  #   ports: 
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=studioghiblibackoffice
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=L@U_4btAYWwW2G:_pc~JDm)[uq;[(ZJ
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/datas
volumes:
  postgres_data: {}
